name: Honeypot
version: '${project.version}'
main: org.reprogle.honeypot.Honeypot
description: Creates honeypot blocks designed to prevent griefing on your server
api-version: '1.18'
load: STARTUP
dependencies:
  server:
    Vault:
      load: AFTER
      required: false
    WorldGuard:
      load: AFTER
      required: false
    GriefPrevention:
      load: AFTER
      required: false
    Lands:
      load: AFTER
      required: false
    PlaceholderAPI:
      load: AFTER
      required: false
authors:
  - TerrorByte
contributors:
  - MattVid#3488
  - Jammers
  - melaniebeedot
  - siyukatu#4489
  - HaHaWTH
  - Casper#9647
  - SandwichBtw
permissions:
  - honeypot.gui
  - honeypot.commands
  - honeypot.create
  - honeypot.break
  - honeypot.remove
  - honeypot.locate
  - honeypot.exempt
  - honeypot.notify
  - honeypot.reload
  - honeypot.update
  - honeypot.history
  - honeypot.teleport
  - honeypot.debug
  - honeypot.migrate
  - honeypot.*
default-perm: op